name: Generate Snake Animation

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: dblade02
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
